# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

QS_Weights_cpp <- function(x) {
    .Call(`_MultiHorizonSPA_QS_Weights_cpp`, x)
}

QS_cpp <- function(y) {
    .Call(`_MultiHorizonSPA_QS_cpp`, y)
}

Get_MBB_ID_cpp <- function(TT, L) {
    .Call(`_MultiHorizonSPA_Get_MBB_ID_cpp`, TT, L)
}

MBB_Variance_cpp <- function(y, L) {
    .Call(`_MultiHorizonSPA_MBB_Variance_cpp`, y, L)
}

Bootstrap_aSPA_cpp <- function(Loss_Diff, weights, L, B, ncores, seed) {
    .Call(`_MultiHorizonSPA_Bootstrap_aSPA_cpp`, Loss_Diff, weights, L, B, ncores, seed)
}

Bootstrap_uSPA_cpp <- function(Loss_Diff, L, B, ncores, seed) {
    .Call(`_MultiHorizonSPA_Bootstrap_uSPA_cpp`, Loss_Diff, L, B, ncores, seed)
}

Test_aSPA_cpp <- function(LossDiff, weights, L, B, ncores, seed) {
    .Call(`_MultiHorizonSPA_Test_aSPA_cpp`, LossDiff, weights, L, B, ncores, seed)
}

Test_uSPA_cpp <- function(LossDiff, L, B, ncores, seed) {
    .Call(`_MultiHorizonSPA_Test_uSPA_cpp`, LossDiff, L, B, ncores, seed)
}

MultiHorizonMCS_cpp <- function(Losses, alpha_t, alpha_mcs, weights, L, B, unif_or_avg, ncores, seed) {
    .Call(`_MultiHorizonSPA_MultiHorizonMCS_cpp`, Losses, alpha_t, alpha_mcs, weights, L, B, unif_or_avg, ncores, seed)
}

